*** Variables ***
${USER_MANAGEMENT}       //span[text()='User Management ']
${ADD_BUTTON}            //button[text()=' Add ']
${ADD_USER_TITLE}        //h6[text()='Add User']
${EMPLOYEE_HINT}         css:input[placeholder="Type for hints..."]
${NO_RECORDS_FOUND}      //*[text()='No Records Found']
${INVALID_MESSAGE}       //span[text()='Invalid']
${ADMIN_USERNAME_INPUT}  (//input[@class='oxd-input oxd-input--active'])[2]
${MIN5_MESSAGE}          //span[text()='Should be at least 5 characters']
${ALREADY_EXISTS}        //span[text()='Already exists']
${LOWERCASE_RULE}        //span[text()='Your password must contain minimum 1 lower-case letter']
&{DIALOG}                UserManagment=${USER_MANAGEMENT}    addButton=${ADD_BUTTON}    userNameInput=(//input[@autocomplete='off'])[1]    userPassword=(//input[@type='password'])[1]

${USER_ROLE_DROPDOWN}   (//div[@class='oxd-select-text-input'])[1]
${STATUS_DROPDOWN}      (//div[@class='oxd-select-text-input'])[2]
${ROLE_ADMIN_OPTION}    //span[text()='Admin']
${ROLE_ESS_OPTION}      //span[text()='ESS']
${STATUS_ENABLED_OPTION}    //span[text()='Enabled']
${STATUS_DISABLED_OPTION}   //span[text()='Disabled']
${EMPLOYEE_OPTION_PETER}    //*[text()='Peter Mac Anderson']
${PASSWORD_INPUT_1}         (//input[@type='password'])[1]
${PASSWORD_INPUT_2}         (//input[@type='password'])[2]
${SAVE_BUTTON}              (//div[@class='oxd-form-actions']//button)[2]
${SUCCESS_TOAST}            //*[text()='Success']
${YES_DELETE_BUTTON}        //button[normalize-space()='Yes, Delete']